# Generated by Django 2.2.8 on 2022-06-15 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=30)),
                ('profile_pic', models.ImageField(blank='true', default='default.png', upload_to='profile/')),
                ('description', models.TextField(max_length=300)),
                ('bio', models.TextField()),
                ('location', models.TextField(max_length=30)),
                ('date_joined', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
